@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.github.elenterius.combat_commons.compat.pehkui;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;