@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.github.elenterius.combat_commons.compat.pehkui;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;