@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.github.elenterius.combat_commons.enchantment;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;