@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.github.elenterius.combat_commons.utils;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;